"""
Utility module for generating RS-274X Gerber files and Excellon drill files.
Provides basic primitives for traces, pads, and holes.
"""

import os
from dataclasses import dataclass
from typing import List, Tuple


@dataclass
class Point:
    """A point in 2D space (in millimeters)."""
    x: float
    y: float

    def to_inches(self) -> Tuple[float, float]:
        """Convert to inches (Gerber default)."""
        return (self.x / 25.4, self.y / 25.4)


class GerberFile:
    """Represents a single Gerber (RS-274X) layer file."""

    def __init__(self, name: str = "layer"):
        self.name = name
        self.apertures = {}  # aperture_id -> aperture definition
        self.aperture_count = 10  # Start numbering from D10
        self.commands = []

    def add_aperture(self, aperture_type: str, size: float) -> int:
        """
        Add a circular aperture (flash pad) and return its D-code.
        aperture_type: "circle" or "rect"
        size: diameter in inches
        """
        aid = self.aperture_count
        self.apertures[aid] = (aperture_type, size)
        self.aperture_count += 1
        return aid

    def select_aperture(self, d_code: int):
        """Select an aperture by D-code."""
        self.commands.append(f"D{d_code}*")

    def move_to(self, x: float, y: float):
        """Move to position without drawing (in inches)."""
        x_int = int(x * 1e5)  # Convert to 2.5 decimal format
        y_int = int(y * 1e5)
        self.commands.append(f"X{x_int}Y{y_int}D02*")

    def line_to(self, x: float, y: float):
        """Draw line to position (in inches)."""
        x_int = int(x * 1e5)
        y_int = int(y * 1e5)
        self.commands.append(f"X{x_int}Y{y_int}D01*")

    def flash(self, x: float, y: float):
        """Flash (expose) aperture at position (in inches)."""
        x_int = int(x * 1e5)
        y_int = int(y * 1e5)
        self.commands.append(f"X{x_int}Y{y_int}D03*")

    def draw_rectangle(self, x1: float, y1: float, x2: float, y2: float):
        """Draw a filled rectangle with the current aperture."""
        self.move_to(x1, y1)
        self.line_to(x2, y1)
        self.line_to(x2, y2)
        self.line_to(x1, y2)
        self.line_to(x1, y1)

    def write_file(self, filepath: str):
        """Write the Gerber file to disk."""
        with open(filepath, 'w') as f:
            # Header
            f.write("G04 RS-274X Gerber file*\n")
            f.write("G04 Generated by gerber_utils.py*\n")
            f.write("%FSLAX25Y25*%\n")  # Format: 2.5 decimal places
            f.write("%MOIN*%\n")  # Inches

            # Aperture definitions
            for aid, (atype, size) in sorted(self.apertures.items()):
                if atype == "circle":
                    f.write(f"%ADD{aid}C,{size}*%\n")
                elif atype == "rect":
                    f.write(f"%ADD{aid}R,{size}X{size}*%\n")

            # Commands
            for cmd in self.commands:
                f.write(cmd + "\n")

            # Footer
            f.write("M02*\n")  # End of file


class DrillFile:
    """Represents an Excellon drill file."""

    def __init__(self):
        self.holes = []  # List of (x, y, diameter) in inches

    def add_hole(self, x: float, y: float, diameter: float):
        """Add a hole at (x, y) with given diameter (in inches)."""
        self.holes.append((x, y, diameter))

    def write_file(self, filepath: str):
        """Write the Excellon drill file to disk."""
        # Collect unique drill sizes
        sizes = sorted(set(hole[2] for hole in self.holes))

        with open(filepath, 'w') as f:
            # Header
            f.write("M48\n")
            f.write("INCH\n")
            f.write("M72\n")  # 2.4 format

            # Tool definitions
            tool_map = {}
            for i, size in enumerate(sizes, start=1):
                tool_id = i
                tool_map[size] = tool_id
                # Convert size to 0.0000 format
                size_str = f"{size:.4f}"
                f.write(f"T{tool_id}C{size_str}\n")

            f.write("%\n")  # End of header

            # Drill positions
            for x, y, diameter in self.holes:
                tool_id = tool_map[diameter]
                x_int = int(x * 10000)  # 2.4 format
                y_int = int(y * 10000)
                f.write(f"T{tool_id}\n")
                f.write(f"X{x_int:05d}Y{y_int:05d}\n")

            # Footer
            f.write("M30\n")


def mm_to_inch(mm: float) -> float:
    """Convert millimeters to inches."""
    return mm / 25.4
