"""
Utility module for generating RS-274X Gerber files and Excellon drill files.
Provides basic primitives for traces, pads, and holes.
"""

import os


class GerberFile:
    """Represents a single Gerber (RS-274X) layer file."""

    def __init__(self, name: str = "layer"):
        self.name = name
        self.apertures = {}  # aperture_id -> aperture definition
        self.aperture_count = 10  # Start numbering from D10
        self.commands = []

    def add_aperture(self, aperture_type: str, size: float, height: float = None) -> int:
        """
        Add an aperture and return its D-code.
        aperture_type: "circle" or "rect"
        size: diameter (circle) or width (rect) in inches
        height: height in inches (rect only, defaults to size if omitted)
        """
        aid = self.aperture_count
        self.apertures[aid] = (aperture_type, size, height)
        self.aperture_count += 1
        return aid

    def select_aperture(self, d_code: int):
        """Select an aperture by D-code."""
        self.commands.append(f"D{d_code}*")

    def move_to(self, x: float, y: float):
        """Move to position without drawing (in inches)."""
        x_int = int(x * 1e5)  # Convert to 2.5 decimal format
        y_int = int(y * 1e5)
        self.commands.append(f"X{x_int}Y{y_int}D02*")

    def line_to(self, x: float, y: float):
        """Draw line to position (in inches)."""
        x_int = int(x * 1e5)
        y_int = int(y * 1e5)
        self.commands.append(f"X{x_int}Y{y_int}D01*")

    def flash(self, x: float, y: float):
        """Flash (expose) aperture at position (in inches)."""
        x_int = int(x * 1e5)
        y_int = int(y * 1e5)
        self.commands.append(f"X{x_int}Y{y_int}D03*")

    def draw_rectangle(self, x1: float, y1: float, x2: float, y2: float):
        """Draw a rectangle outline with the current aperture."""
        self.move_to(x1, y1)
        self.line_to(x2, y1)
        self.line_to(x2, y2)
        self.line_to(x1, y2)
        self.line_to(x1, y1)

    def fill_rectangle(self, x1: float, y1: float, x2: float, y2: float):
        """Draw a filled (poured) rectangle using G36/G37 region fill."""
        def _coord(x, y):
            return f"X{int(x * 1e5)}Y{int(y * 1e5)}"
        self.commands.append("G36*")
        self.commands.append(f"{_coord(x1, y1)}D02*")
        self.commands.append(f"{_coord(x2, y1)}D01*")
        self.commands.append(f"{_coord(x2, y2)}D01*")
        self.commands.append(f"{_coord(x1, y2)}D01*")
        self.commands.append(f"{_coord(x1, y1)}D01*")
        self.commands.append("G37*")

    def write_file(self, filepath: str):
        """Write the Gerber file to disk."""
        with open(filepath, 'w') as f:
            # Header
            f.write("G04 RS-274X Gerber file*\n")
            f.write("G04 Generated by gerber_utils.py*\n")
            f.write("%FSLAX25Y25*%\n")  # Format: 2.5 decimal places
            f.write("%MOIN*%\n")  # Inches

            # Aperture definitions
            for aid, (atype, size, height) in sorted(self.apertures.items()):
                if atype == "circle":
                    f.write(f"%ADD{aid}C,{size}*%\n")
                elif atype == "rect":
                    h = height if height is not None else size
                    f.write(f"%ADD{aid}R,{size}X{h}*%\n")

            # Commands
            for cmd in self.commands:
                f.write(cmd + "\n")

            # Footer
            f.write("M02*\n")  # End of file


class DrillFile:
    """Represents an Excellon drill file."""

    def __init__(self):
        self.holes = []  # List of (x, y, diameter) in inches

    def add_hole(self, x: float, y: float, diameter: float):
        """Add a hole at (x, y) with given diameter (in inches)."""
        self.holes.append((x, y, diameter))

    def write_file(self, filepath: str):
        """Write the Excellon drill file to disk."""
        # Collect unique drill sizes
        sizes = sorted(set(hole[2] for hole in self.holes))

        with open(filepath, 'w') as f:
            # Header
            f.write("M48\n")
            f.write("INCH\n")
            f.write("M72\n")  # 2.4 format

            # Tool definitions
            tool_map = {}
            for i, size in enumerate(sizes, start=1):
                tool_id = i
                tool_map[size] = tool_id
                # Convert size to 0.0000 format
                size_str = f"{size:.4f}"
                f.write(f"T{tool_id}C{size_str}\n")

            f.write("%\n")  # End of header

            # Drill positions grouped by tool
            for size in sizes:
                tool_id = tool_map[size]
                f.write(f"T{tool_id}\n")
                for x, y, diameter in self.holes:
                    if diameter == size:
                        x_int = int(x * 10000)  # 2.4 format
                        y_int = int(y * 10000)
                        f.write(f"X{x_int:05d}Y{y_int:05d}\n")

            # Footer
            f.write("M30\n")


def create_solder_mask(copper_layer, expansion=0.003):
    """
    Create a solder mask layer from a copper layer's pad flashes.
    The mask has openings (slightly larger) at every pad location.
    expansion: how much larger each mask opening is vs the pad (inches).
    """
    import re
    mask = GerberFile(f"soldermask_{copper_layer.name}")

    # Re-create apertures with expansion for mask openings
    aperture_map = {}
    for aid, (atype, size, height) in copper_layer.apertures.items():
        if atype == "circle":
            new_aid = mask.add_aperture("circle", size + expansion)
        elif atype == "rect":
            h = height if height is not None else size
            new_aid = mask.add_aperture("rect", size + expansion, h + expansion)
        aperture_map[aid] = new_aid

    # Copy only flash (D03) commands and aperture selections that precede them
    current_aperture = None
    for cmd in copper_layer.commands:
        if cmd.startswith("D") and cmd.endswith("*") and "X" not in cmd:
            # Aperture selection like "D10*"
            d_code = int(cmd[1:-1])
            if d_code in aperture_map:
                current_aperture = aperture_map[d_code]
                mask.commands.append(f"D{current_aperture}*")
        elif "D03*" in cmd and current_aperture is not None:
            # Flash command — copy as mask opening
            mask.commands.append(cmd)

    return mask


def create_paste_layer(copper_layer, smd_aperture_ids):
    """
    Create a solder paste stencil layer from specific SMD pad apertures.
    smd_aperture_ids: list of D-codes that correspond to SMD pads (not TH or vias).
    """
    paste = GerberFile(f"paste_{copper_layer.name}")

    # Copy the SMD apertures
    aperture_map = {}
    for aid in smd_aperture_ids:
        if aid in copper_layer.apertures:
            atype, size, height = copper_layer.apertures[aid]
            new_aid = paste.add_aperture(atype, size, height)
            aperture_map[aid] = new_aid

    # Copy only flash commands for those apertures
    current_aperture = None
    active = False
    for cmd in copper_layer.commands:
        if cmd.startswith("D") and cmd.endswith("*") and "X" not in cmd:
            d_code = int(cmd[1:-1])
            if d_code in aperture_map:
                current_aperture = aperture_map[d_code]
                paste.commands.append(f"D{current_aperture}*")
                active = True
            else:
                active = False
        elif "D03*" in cmd and active:
            paste.commands.append(cmd)

    return paste


def mm_to_inch(mm: float) -> float:
    """Convert millimeters to inches."""
    return mm / 25.4
